// Generated by Visual Studio scaffolding

using System.Web.Mvc;
using Octogami.DutyHours.Application;

namespace Octogami.DutyHours.Web.Controllers
{
	public class HomeController : Controller
	{
		private readonly ITest _test;

		public HomeController(ITest test)
		{
			_test = test;
		}

		public ActionResult Index()
		{
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			_test.Throw("Just testing the IoC container");

			return View();
		}
	}
}