// Generated by Visual Studio scaffolding

using System.Linq;
using System.Web.Mvc;
using Octogami.DutyHours.Application;
using Octogami.DutyHours.DataAccess;

namespace Octogami.DutyHours.Web.Controllers
{
	public class HomeController : Controller
	{
		private readonly ITest _test;
		private readonly ApplicationDbContext _db;

		public HomeController(ITest test, ApplicationDbContext db)
		{
			_test = test;
			_db = db;
		}

		public ActionResult Index()
		{
			var usernames = _db.Users.Select(x => x.UserName).ToList();
			return View(usernames);
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			_test.Throw("Just testing the IoC container");

			return View();
		}
	}
}