// <auto-generated />
namespace Octogami.DutyHours.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialShiftsAndUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialShiftsAndUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201604301914393_InitialShiftsAndUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
